// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd1TG_QdIl1EHSd-ZkptE94d3GVLbyBqw',
    appId: '1:691078404023:web:43e70f214c9175cd68ba32',
    messagingSenderId: '691078404023',
    projectId: 'mastermax-2030-backend',
    authDomain: 'mastermax-2030-backend.firebaseapp.com',
    storageBucket: 'mastermax-2030-backend.firebasestorage.app',
    measurementId: 'G-KJ6FQP6T1P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjAnZhLH1DZznK1z5siYvFwGgtL84FvZw',
    appId: '1:691078404023:android:3cfb1da3e6b5ca5068ba32',
    messagingSenderId: '691078404023',
    projectId: 'mastermax-2030-backend',
    storageBucket: 'mastermax-2030-backend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2OWNdjbeROIR9Fa_z6rVzHhDFHn_Q4Mg',
    appId: '1:691078404023:ios:8e4240191109032868ba32',
    messagingSenderId: '691078404023',
    projectId: 'mastermax-2030-backend',
    storageBucket: 'mastermax-2030-backend.firebasestorage.app',
    iosBundleId: 'com.example.mastermax2030',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2OWNdjbeROIR9Fa_z6rVzHhDFHn_Q4Mg',
    appId: '1:691078404023:ios:8e4240191109032868ba32',
    messagingSenderId: '691078404023',
    projectId: 'mastermax-2030-backend',
    storageBucket: 'mastermax-2030-backend.firebasestorage.app',
    iosBundleId: 'com.example.mastermax2030',
  );
}
